# Generated by Django 4.2.6 on 2023-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_club_yili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='record_sotuv',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='record_trans',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
